# Version for NakasuKasumi mod
# base on Yuuki Asuna mod

find_package(Git)

set(MOD_BUILD "Nakasu Kasumi")

# X265_HEAD_TAG
execute_process(COMMAND
    ${GIT_EXECUTABLE} describe --tags HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_HEAD_TAG
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )
# X265_HEAD_TAG_NUM
execute_process(COMMAND
    ${GIT_EXECUTABLE} describe --abbrev=0 --tags
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_HEAD_TAG_NUM
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )
# X265_HEAD_HASH
execute_process(COMMAND
    ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_HEAD_HASH
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )

# X265_CURRENT_BRANCH
execute_process(COMMAND
    ${GIT_EXECUTABLE} branch --show-current
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_CURRENT_BRANCH
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )

if("${X265_CURRENT_BRANCH}" STREQUAL "master-mod")
    set(X265_BASE_BRANCH "bitbucket-master")
elseif("${X265_CURRENT_BRANCH}" STREQUAL "stable-mod")
    set(X265_BASE_BRANCH "bitbucket-stable")
else()
    set(X265_BASE_BRANCH "${X265_CURRENT_BRANCH}")
endif()

# X265_BASE_TAG: x265 base tag & commit
execute_process(COMMAND
    ${GIT_EXECUTABLE} describe --tags origin/${X265_BASE_BRANCH}
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_BASE_TAG
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )
# X265_BASE_TAG_NUM: x265 base tag
execute_process(COMMAND
    ${GIT_EXECUTABLE} describe --abbrev=0 --tags origin/${X265_BASE_BRANCH}
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_BASE_TAG_NUM
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )
# X265_BASE_HASH
execute_process(COMMAND
    ${GIT_EXECUTABLE} rev-parse --short origin/${X265_BASE_BRANCH}
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE X265_BASE_HASH
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    )

if(${X265_BASE_TAG} STREQUAL ${X265_BASE_TAG_NUM})
    set(X265_BASE_DISTANCE "0")
    set(X265_BASE_COMMIT "${X265_BASE_HASH}")
else()
    string(REPLACE "-" ";" X265_BASE_TAG_ARR ${X265_BASE_TAG})
    list(GET X265_BASE_TAG_ARR 1 X265_BASE_DISTANCE)
    list(GET X265_BASE_TAG_ARR 2 X265_BASE_COMMIT)
endif()

string(REPLACE "-" ";" X265_HEAD_TAG_ARR ${X265_HEAD_TAG})
list(GET X265_HEAD_TAG_ARR 0 X265_ORIG_TAG)
list(GET X265_HEAD_TAG_ARR 1 X265_HEAD_DISTANCE)
list(GET X265_HEAD_TAG_ARR 2 X265_HEAD_COMMIT)

set(X265_LATEST_TAG "${X265_ORIG_TAG}")

math(EXPR X265_VERSION_DIFF "${X265_HEAD_DISTANCE} - ${X265_BASE_DISTANCE}")
set(X265_VERSION "${X265_LATEST_TAG}+${X265_BASE_DISTANCE}-${X265_BASE_COMMIT}+${X265_VERSION_DIFF}-g${X265_HEAD_HASH}")

message(STATUS "x265 Mod: ${MOD_BUILD}")
message(STATUS "x265 Release Version: ${X265_VERSION}")
